"""initial

Revision ID: be293b04ff32
Revises: 
Create Date: 2025-11-15 14:08:12.408717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be293b04ff32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_sets',
    sa.Column('set_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('set_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.String(length=50), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('bloom_level', sa.Enum('remember', 'understand', 'apply', 'analyze', 'evaluate', 'create'), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard'), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('choices',
    sa.Column('choice_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=1), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('choice_id')
    )
    op.create_table('exams',
    sa.Column('exam_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_table('media',
    sa.Column('media_id', sa.String(length=50), nullable=False),
    sa.Column('question_id', sa.String(length=50), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('image', 'video', 'audio', 'pdf'), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id')
    )
    op.create_table('question_set_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_id', sa.String(length=50), nullable=True),
    sa.Column('question_id', sa.String(length=50), nullable=True),
    sa.Column('order_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['set_id'], ['question_sets.set_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_set_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_set_questions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_set_questions_set_id'), ['set_id'], unique=False)

    op.create_table('question_tags',
    sa.Column('question_id', sa.String(length=50), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'tag_id')
    )
    op.create_table('exam_questions',
    sa.Column('exam_id', sa.String(length=50), nullable=False),
    sa.Column('question_id', sa.String(length=50), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_questions')
    op.drop_table('question_tags')
    with op.batch_alter_table('question_set_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_set_questions_set_id'))
        batch_op.drop_index(batch_op.f('ix_question_set_questions_question_id'))

    op.drop_table('question_set_questions')
    op.drop_table('media')
    op.drop_table('exams')
    op.drop_table('choices')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('questions')
    op.drop_table('question_sets')
    # ### end Alembic commands ###
